version: '3'
services:
  db:
    image: mongo:4.4
    container_name: db
    
    ports:
      - "4000:27017"
    restart: always
        
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=tracker
    restart: "no"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # track-sensor:
  #   image: andywarhurst/track-sensor:v1
  #   ports:
  #     - "4003:3001"
  #   environment:
  #     - KAFKA_ADVERTISED_HOST="localhost"
  #     - KAFKA_ADVERTISED_PORT=9092
  #     - KAFKA_SESSION_PREFIX=""
  #   restart: "no"

  # simple-tracker:
  #   image: andywarhurst/simple-tracker:v1
  #   ports:
  #     - "4004:3002"
  #   environment:
  #     - KAFKA_ADVERTISED_HOST="localhost"
  #     - KAFKA_ADVERTISED_PORT=9092
  #     - KAFKA_SESSION_PREFIX=""
  #   restart: "no"

  # track-manager:
  #   image: andywarhurst/track-manager:v1
  #   ports:
  #     - "4002:3000"
  #   environment:
  #     - KAFKA_ADVERTISED_HOST="localhost"
  #     - KAFKA_ADVERTISED_PORT=9092
  #     - KAFKA_SESSION_PREFIX=""
  #     - DBHOSTNAME=mongodb://db:27017
  #     - DBNAME=trackdb
  #   restart: "no"
